name: Build and deploy a container to an Azure Web App

env:
  AZURE_WEBAPP_NAME: nginx-hello

on:
  push:
    branches: 
      - master
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1.10.0
        with:
          registry: kimodocker.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t kimodocker.azurecr.io/nginx-hello:latest
          docker push kimodocker.azurecr.io/nginx-hello:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'hello-nginx-kimo'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'kimodocker.azurecr.io/nginx-hello:latest'
